fix example,add numpy check and install for 0_launch_kernel example
Co-authored-by: liukejin<liukejin@huawei.com>



# message auto-generated for no-merge-commit merge:
!691 merge fix_numpy into master

fix example,add numpy check and install for 0_launch_kernel example

Created-by: liukejin
Commit-by: liukejin
Merged-by: cann-robot
Description: ## 描述
<!--在这里详细描述你的改动，包括改动的原因和所采取的方法。-->
fix example,add numpy check and install for 0_launch_kernel example
修改方案：
1. 检查numpy模块是否安装
	1）若安装，则直接执行后续流程
    2）若未安装，使用pip安装numpy
 2. 资料执行`bash run.sh -r simple` 前加上依赖python模块numpy的说明

## 关联的Issue
<!-- 如果这个PR是为了解决特定的Issue，请在这里提供Issue链接。例如：关联Issue #000-->
关联Issue [#166](https://gitcode.com/cann/runtime/issues/166) 
## 测试
<!--描述进行了哪些测试来验证你的改动。包括但不限于二级冒烟、算子泛化等。-->
1. 复现：
```
[100%] Built target ascendc_kernels_placeholder_fatbin_obj
-- Install configuration: "Debug"
-- Installing: /home/lkj/runtime-master/example/kernel/0_launch_kernel/out/bin/ascendc_kernels_bbit
Traceback (most recent call last):
  File "scripts/gen_data.py", line 15, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
2. 修复验证：
```
-- Install configuration: "Debug"
-- Installing: /home/kj/runtime-fix_numpy/example/kernel/0_launch_kernel/out/bin/ascendc_kernels_bbit
checking for numpy dependency...
numpy not found. installing numpy...
Looking in indexes: http://mirrors.tools.huawei.com/pypi/simple
Collecting numpy
  Downloading http://mirrors.tools.huawei.com/pypi/packages/6d/ad/ff3b21ebfe79a4d25b4a4f8e5cf9fd44a204adb6b33c09010f566f51027a/numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 5.1 MB/s eta 0:00:00
Installing collected packages: numpy
  WARNING: The scripts f2py, f2py3 and f2py3.7 are installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
te 0.4.0 requires ml-dtypes, which is not installed.
Successfully installed numpy-1.21.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
numpy installation completed.

```
执行成功
```
7b56ba35d8799e7cabbfd9ebd1bbe82c  output/golden.bin
7b56ba35d8799e7cabbfd9ebd1bbe82c  output/output_z.bin
error ratio: 0.0000, tolerance: 0.0010
[SUCCESS] result correct
```

## 文档更新
<!--如果这个PR包含文档的更新，请在这里指出。例如：更新了README.md文件。-->
example/kernel/0_launch_kernel/README.md
## 类型标签
<!--  [x] 表示选中 -->
- [x] Bug修复
- [ ] 新特性
- [ ] 性能优化
- [ ] 文档更新
- [ ] 其他，请描述：




See merge request: cann/runtime!691